imageRepository: artifacts.developer.gov.bc.ca/docker-remote/redis
imageTag: 7.4.6

redisPort: 6379
sentinelPort: 26379
persistentVolumeSize: 1Gi
persistentVolumeClass: netapp-block-standard

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 512Mi

password: ~
