apiVersion: v2
name: ECER
description: A Helm chart for ECER
type: application
version: 1.0.1
appVersion: "1.0.1"

dependencies:
  - name: redis
    alias: redis
    version: 1.0.1
    condition: redis.enabled
    repository: "file://../redis"
