name: Promote to Prod

env:
  # üñäÔ∏è EDIT your repository secrets to log into your OpenShift cluster and set up the context.
  # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
  # To get a permanent token, refer to https://github.com/redhat-actions/oc-login/wiki/Using-a-Service-Account-for-GitHub-Actions
  OPENSHIFT_SERVER: ${{ vars.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.ECER_NAMESPACE_NO_ENV }}-tools
  APP_ENVIRONMENT_DESTINATION: "prod"

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
    inputs:
      app_environment_source:
        description: "Environment image source for deployment"
        required: true
        type: choice
        options:
          - efxtest
          - uat

jobs:
  openshift-cd:
    name: Promote Image
    runs-on: ubuntu-22.04
    environment: prod

    outputs:
      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

        # https://github.com/redhat-actions/oc-login#readme
      - name: Tag in OpenShift
        run: |
          set -eux
          # Login to OpenShift and select project
          oc login --token=${{ env.OPENSHIFT_TOKEN }} --server=${{ env.OPENSHIFT_SERVER }}
          oc project ${{ env.OPENSHIFT_NAMESPACE }}

          echo promoting ${{inputs.app_environment_source}} imagestream to ${{env.APP_ENVIRONMENT_DESTINATION}}

          #grabs the image sha for our input environments using jq
          API_IMAGE_SHA=$(oc get is api -o json | jq -r '.spec.tags[] | select(.name == "${{inputs.app_environment_source}}").from.name')
          REGISTRY_PORTAL_IMAGE_SHA=$(oc get is registry-portal -o json | jq -r '.spec.tags[] | select(.name == "${{inputs.app_environment_source}}").from.name')
          # PSP_PORTAL_IMAGE_SHA=$(oc get is psp-portal -o json | jq -r '.spec.tags[] | select(.name == "${{inputs.app_environment_source}}").from.name')

          echo registry-portal image sha being promoted: $REGISTRY_PORTAL_IMAGE_SHA
          echo api image sha being promoted: $API_IMAGE_SHA
          # echo psp-portal image sha being promoted: $PSP_PORTAL_IMAGE_SHA

          oc tag -n ${{env.OPENSHIFT_NAMESPACE}} registry-portal:${{inputs.app_environment_source}} registry-portal:${{env.APP_ENVIRONMENT_DESTINATION}}
          oc tag -n ${{env.OPENSHIFT_NAMESPACE}} api:${{inputs.app_environment_source}} api:${{env.APP_ENVIRONMENT_DESTINATION}}
          # oc tag -n ${{env.OPENSHIFT_NAMESPACE}} psp-portal:${{inputs.app_environment_source}} psp-portal:${{env.APP_ENVIRONMENT_DESTINATION}}
