name: PROD - Deploy ECER Clients Keycloak Infrastructure As Code
on:
  workflow_dispatch:
jobs:
  keycloak-infrastructure-as-code:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: check out repository
        uses: actions/checkout@v5
      - name: run script
        uses: actions/github-script@v8
        env:
          KC_REALM_ID: "${{ secrets.KC_REALM_ID }}"
          KC_ENVIRONMENT: "prod"
          KC_CLIENT_ID: ${{ secrets.KC_CLIENT_ID }}
          KC_CLIENT_SECRET: ${{ secrets.KC_CLIENT_SECRET }}
        with:
          script: |
            const { main } = require('./tools/keycloak/script.js');

      - run: echo "üçè This job's status is ${{ job.status }}."
